[package]
name = "mustachestory"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
handlebars = "6.3.0"
mustache = "0.9.0"
tokio = { version = "1.0", features = ["full"] }
